# {{{ visual
[[plugins]]
repo = 'tomasr/molokai'
hook_add = 'colorscheme molokai'
lazy = 0

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
# }}}

# {{{ accessibility
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = 'CtrlP'
on_map = '<c-p>'
# }}}

# {{{ complete
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
if = 'has("lua")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
if = 'has("nvim")'
# }}}

# {{{ execute
[[plugins]]
repo = 'Shougo/vimproc.vim'

    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin = 'make -f make_cygwin.mak'
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
depends = 'vimproc'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'quickrun'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
on_cmd = ['WatchdogsRun', 'WatchdogsRunSilent', 'WatchdogsRunSweep']
depends = 'shabadou'
# }}}

# {{{ haskell
[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
# }}}

# {{{ python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
depends = 'auto-python-neovim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'
# }}}

# {{{ latex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
# }}}

# {{{ toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
# }}}

# {{{ jade
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'
# }}}
# vim:foldmethod=marker
