[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_i = 1
on_ft = 'go'
depends = 'deoplete'
build = 'make'
