# {{{ visual
[[plugins]]
repo = 'tomasr/molokai'
lazy = 0
hook_add = '''
colorscheme molokai
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
augroup hook_add_indent_guides
    execute 'autocmd!'
    execute 'autocmd VimEnter * call dein#source("indent-guides")'
augroup END
'''

hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_default_mapping = 0
let g:indent_guides_auto_colors = 0
highlight IndentGuidesOdd  ctermbg=234 guibg=#252525
highlight IndentGuidesEven ctermbg=235 guibg=#333333
'''

hook_post_source = '''
IndentGuidesEnable
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
let g:context_filetype#filetypes = {}
let g:context_filetype#filetypes['toml'] =
            \ [
            \   { 'filetype':'vim'
            \   , 'start':'^\s*hook_\(add\|source\|post_source\)\s*=\s*\('.'""'.'"'.'\|'."''"."'".'\)'
            \   , 'end':'\2'
            \   }
            \ ]
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype'
on_ft = ['html', 'vim', 'toml']
hook_source = '''
let g:precious_enable_switch_CursorMoved = {"*" : 0}
let g:precious_enable_switch_CursorMoved_i = {"*" : 0}

augroup on_source_precious
    execute 'autocmd!'
    execute 'autocmd InsertEnter * PreciousSwitch'
augroup END
'''
# }}}

# {{{ complete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
'''
# }}}

# {{{ accessibility
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = 'CtrlP'
on_map = '<c-p>'
hook_source = '''
let g:ctrlp_working_path_mode = "ra"
'''
# }}}

# {{{ execute
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
elseif dein#util#_is_mac()
    let cmd = 'make -f make_mac.mak'
else
    let cmd = 'make -f make_unix.mak'
endif

let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
depends = 'vimproc'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'quickrun'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
on_cmd = ['WatchdogsRun', 'WatchdogsRunSilent', 'WatchdogsRunSweep']
depends = 'shabadou'

hook_add = '''
augroup hook_add_vim_watchdogs
    execute 'autocmd!'
    execute 'autocmd BufWritePre * call dein#source("watchdogs") | autocmd! hook_add_vim_watchdogs'
augroup END
'''

hook_source = '''
if !exists('g:quickrun_config')
    let g:quickrun_config = {}
endif

let g:quickrun_config['python/watchdogs_checker'] =
            \ { 'type': 'watchdogs_checker/flake8'
            \ , 'runner/vimproc/updatetime': 10
            \ }

let g:quickrun_config['watchdogs_checker/tsc'] =
            \ { 'exec': '%c' }

let g:watchdogs_check_BufWritePost_enable = 1
let g:watchdogs_check_CursorHold_enable = 1
'''
# }}}

# {{{ toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
# }}}

# {{{ jade
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'
# }}}

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

# vim:foldmethod=marker
