# {{{ visual
[[plugins]]
repo = 'tomasr/molokai'
lazy = 0
hook_add = '''
if dein#tap('molokai')
    colorscheme molokai
endif
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = 'call local#dein#vim_indent_guides#hook_add()'
hook_source = 'call local#dein#vim_indent_guides#hook_source()'
hook_post_source = 'IndentGuidesEnable'

[[plugins]]
repo = 'itchyny/lightline.vim'
lazy = 0
hook_add = 'call local#dein#lightline#hook_add()'
# }}}

# {{{ operator
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'operator-user'
hook_add = 'call local#dein#operator#surround_hook_add()'
lazy = 0
# }}}

# {{{ complete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = 'call local#dein#deoplete#hook_source()'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
# }}}

# {{{ accessibility
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = 'CtrlP'
on_map = '<c-p>'
hook_source = "call local#dein#ctrlp#hook_source()"
# }}}

# {{{ execute
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_add = 'call local#dein#vimproc#hook_add()'

[[plugins]]
repo = 'neomake/neomake'
hook_source = 'call local#dein#neomake#hook_source()'
on_event = 'BufWritePost'
# }}}

# vim:foldmethod=marker
