[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1
depends = 'auto-python-neovim'
hook_source = 'call local#dein#jedi#hook_source()'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
if = 'has("nvim")'
on_i = 1
on_ft = 'python'
depends = ['deoplete', 'jedi']
