[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
depends = 'auto-python-neovim'
hook_source = '''
let g:jedi#force_py_version = str2nr(system('python -c "import sys; print(sys.version_info.major)"'))

if dein#tap('neocomplete') || dein#tap('deoplete')
    let g:jedi#show_call_signatures = 0
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#completions_enabled = 0
    let g:jedi#popup_on_dot = 0

    if dein#tap('neocomplete')
        if !exists('g:neocomplete#sources#omni#input_patterns')
            let g:neocomplete#sources#omni#input_patterns = {}
        endif
        let g:neocomplete#sources#omni#input_patterns.python =
                    \ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
    endif
endif

augroup hook_source_jedi
    execute 'autocmd!'
    execute 'autocmd FileType python setlocal omnifunc=jedi#completions completeopt-=preview'
augroup END
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
if = 'has("nvim")'
on_i = 1
on_ft = 'python'
depends = ['deoplete', 'jedi']
