[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
depends = 'vimproc'
on_ft = 'typescript'
hook_source = 'call local#dein#tsuquyomi#hook_source()'

[[plugins]]
repo = 'mhartington/deoplete-typescript'
depends = ['deoplete']
on_ft = 'typescript'
