[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'
depends = ['vimproc', 'typescript']
hook_add = 'call local#dein#tsuquyomi#hook_add()'
lazy = 0

[[plugins]]
repo = 'mhartington/deoplete-typescript'
depends = ['deoplete']
on_ft = 'typescript'
